const chapters = [50, 40, 27, 36, 34, 24, 21, 4, 31, 24, 22, 25, 29, 36, 10, 13, 10, 42, 150, 31, 12, 8, 66, 52, 5, 48, 12, 14, 3, 9, 1, 4, 7, 3, 3, 3, 2, 14, 4, 28, 16, 24, 21, 28, 16, 16, 13, 6, 6, 4, 4, 5, 3, 6, 4, 3, 1, 13, 5, 5, 3, 5, 1, 1, 1, 22]
const bibleBooks = [
    'Genesis',
    'Exodus',
    'Leviticus',
    'Numbers',
    'Deuteronomy',
    'Joshua',
    'Judges',
    'Ruth',
    '1 Samuel',
    '2 Samuel',
    '1 Kings',
    '2 Kings',
    '1 Chronicles',
    '2 Chronicles',
    'Ezra',
    'Nehemiah',
    'Eshter',
    'Job',
    'Psalms',
    'Proverbs',
    'Ecclesiastes',
    'Song of Songs',
    'Isaiah',
    'Jeremiah',
    'Lamentations',
    'Ezekiel',
    'Daniel',
    'Hosea',
    'Joel',
    'Amos',
    'Obadiah',
    'Jonah',
    'Micah',
    'Nahum',
    'Habakkuk',
    'Zephaniah',
    'Haggai',
    'Zechariah',
    'Malachi',
    'Matthew',
    'Mark',
    'Luke',
    'John',
    'Acts',
    'Romans',
    '1 Corinthians',
    '2 Corinthians',
    'Galatians',
    'Ephisians',
    'Philippians',
    'Colossians',
    '1 Thessalonians',
    '2 Thessalonians',
    '1 Timothy',
    '2 Timothy',
    'Titus',
    'Philemon',
    'Hebrews',
    'James',
    '1 Peter',
    '2 Peter',
    '1 John',
    '2 John',
    '3 John',
    'Jude',
    'Revelation'
];

const bibleBooks = [
	{name: 'Genesis', chapters: 50},
	{name: 'Exodus', chapters: 40},
	{name: 'Leviticus', chapters: 27},
	{name: 'Numbers', chapters: 36},
	{name: 'Deuteronomy', chapters: 34},
	{name: 'Joshua', chapters: 24},
	{name: 'Judges', chapters: 21},
	{name: 'Ruth', chapters: 4},
	{name: '1 Samuel', chapters: 31},
	{name: '2 Samuel', chapters: 24},
	{name: '1 Kings', chapters: 22},
	{name: '2 Kings', chapters: 25},
	{name: '1 Chronicles', chapters: 29},
	{name: '2 Chronicles', chapters: 36},
	{name: 'Ezra', chapters: 10},
	{name: 'Nehemiah', chapters: 13},
	{name: 'Eshter', chapters: 10},
	{name: 'Job', chapters: 42},
	{name: 'Psalms', chapters: 150},
	{name: 'Proverbs', chapters: 31},
	{name: 'Ecclesiastes', chapters: 12},
	{name: 'Song of Songs', chapters: 8},
	{name: 'Isaiah', chapters: 66},
	{name: 'Jeremiah', chapters: 52},
	{name: 'Lamentations', chapters: 5},
	{name: 'Ezekiel', chapters: 48},
	{name: 'Daniel', chapters: 12},
	{name: 'Hosea', chapters: 14},
	{name: 'Joel', chapters: 3},
	{name: 'Amos', chapte*rs: 9},
	{name: 'Obadiah', chapters: 1},
	{name: 'Jonah', chapters: 4},
	{name: 'Micah', chapters: 7},
	{name: 'Nahum', chapters: 3},
	{name: 'Habakkuk', chapters: 3},
	{name: 'Zephaniah', chapters: 3},
	{name: 'Haggai', chapters: 2},
	{name: 'Zechariah', chapters: 14},
	{name: 'Malachi', chapters: 4},
	{name: 'Matthew', chapters: 28},
	{name: 'Mark', chapters: 16},
	{name: 'Luke', chapters: 24},
	{name: 'John', chapters: 21},
	{name: 'Acts', chapters: 28},
	{name: 'Romans', chapters: 16},
	{name: '1 Corinthians', chapters: 16},
	{name: '2 Corinthians', chapters: 13},
	{name: 'Galatians', chapters: 6},
	{name: 'Ephisians', chapters: 6},
	{name: 'Philippians', chapters: 4},
	{name: 'Colossians', chapters: 4},
	{name: '1 Thessalonians', chapters: 5},
	{name: '2 Thessalonians', chapters: 3},
	{name: '1 Timothy', chapters: 6},
	{name: '2 Timothy', chapters: 4},
	{name: 'Titus', chapters: 3},
	{name: 'Philemon', chapters: 1},
	{name: 'Hebrews', chapters: 13},
	{name: 'James', chapters: 5},
	{name: '1 Peter', chapters: 5},
	{name: '2 Peter', chapters: 3},
	{name: '1 John', chapters: 5},
	{name: '2 John', chapters: 1},
	{name: '3 John', chapters: 1},
	{name: 'Jude', chapters: 1},
	{name: 'Revelation', chapters: 22}
];
